# Generated by Django 5.2 on 2025-05-15 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='flag',
            field=models.BooleanField(default=True),
        ),
    ]
