# Generated by Django 5.2 on 2025-05-09 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
        ('measurements', '0002_temperature_measurement_alter_measurement_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='campaigns',
            field=models.ManyToManyField(blank=True, to='campaigns.campaign'),
        ),
    ]
