# Generated by Django 5.2 on 2025-05-19 11:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("measurements", "0002_alter_measurement_flag"),
    ]

    operations = [
        migrations.AlterField(
            model_name="measurement",
            name="timestamp",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
