# Generated by Django 5.2 on 2025-05-19 12:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("measurements", "0003_alter_measurement_timestamp"),
    ]

    operations = [
        migrations.AddField(
            model_name="measurement",
            name="timestamp_local",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
