# Generated by Django 5.2 on 2025-05-12 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0004_locationtest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LocationTest',
        ),
    ]
