# Generated by Django 5.2 on 2025-05-19 12:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("measurements", "0004_measurement_timestamp_local"),
    ]

    operations = [
        migrations.AlterField(
            model_name="measurement",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
