# Generated by Django 5.2 on 2025-05-13 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0004_locationtest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LocationTest',
        ),
        migrations.AlterField(
            model_name='temperature',
            name='measurement',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='measurements.measurement'),
            preserve_default=False,
        ),
    ]
