# Generated by Django 5.2 on 2025-05-20 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0005_alter_measurement_timestamp'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='temperature',
            constraint=models.CheckConstraint(condition=models.Q(('value__gte', 0)), name='temperature_value_greater_than_zero'),
        ),
        migrations.AddConstraint(
            model_name='temperature',
            constraint=models.CheckConstraint(condition=models.Q(('value__lte', 100)), name='temperature_value_less_than_100'),
        ),
    ]
