# Generated by Django 5.2 on 2025-05-22 12:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0006_temperature_temperature_value_greater_than_zero_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measurement',
            name='timestamp_local',
        ),
        migrations.AddField(
            model_name='measurement',
            name='local_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='measurement',
            name='local_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
