# Generated by Django 5.2 on 2025-05-25 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0007_remove_measurement_timestamp_local_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='water_source',
            field=models.CharField(choices=[('network', 'network'), ('rooftop tank', 'rooftop tank'), ('well', 'well'), ('other', 'other')], max_length=255),
        ),
    ]
