# Generated by Django 5.2 on 2025-06-10 11:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_campaign_campaigns_c_region_16212e_idx_and_more'),
        ('measurements', '0008_alter_measurement_water_source'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='measurement',
            index=models.Index(fields=['location'], name='measurement_locatio_4f5333_idx'),
        ),
        migrations.AddIndex(
            model_name='measurement',
            index=models.Index(fields=['water_source'], name='measurement_water_s_2418f0_idx'),
        ),
        migrations.AddIndex(
            model_name='measurement',
            index=models.Index(fields=['local_date'], name='measurement_local_d_02e1a8_idx'),
        ),
        migrations.AddIndex(
            model_name='measurement',
            index=models.Index(fields=['local_time'], name='measurement_local_t_9495b2_idx'),
        ),
        migrations.AddIndex(
            model_name='measurement',
            index=models.Index(fields=['local_date', 'local_time'], name='measurement_local_d_9b25c6_idx'),
        ),
        migrations.AddIndex(
            model_name='temperature',
            index=models.Index(fields=['value'], name='measurement_value_fcd50e_idx'),
        ),
        migrations.AddConstraint(
            model_name='temperature',
            constraint=models.UniqueConstraint(fields=('measurement',), name='unique_measurement_id'),
        ),
    ]
