# Generated by Django 5.2 on 2025-06-22 13:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_campaign_campaigns_c_region_16212e_idx_and_more'),
        ('measurement_export', '0005_alter_preset_filters'),
        ('measurements', '0009_measurement_measurement_locatio_4f5333_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='location_ref',
            field=models.ForeignKey(blank=True, help_text='Computed reference to location containing this measurement point', null=True, on_delete=django.db.models.deletion.SET_NULL, to='measurement_export.location'),
        ),
        migrations.AddIndex(
            model_name='measurement',
            index=models.Index(fields=['location_ref'], name='measurement_locatio_d9b15b_idx'),
        ),
    ]
