# Generated by Django 5.2 on 2025-06-22 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0010_measurement_location_ref_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='temperature',
            name='temperature_value_greater_than_zero',
        ),
        migrations.RemoveConstraint(
            model_name='temperature',
            name='temperature_value_less_than_100',
        ),
        migrations.AddConstraint(
            model_name='temperature',
            constraint=models.CheckConstraint(condition=models.Q(('value__gt', 0)), name='temperature_value_greater_than_zero'),
        ),
        migrations.AddConstraint(
            model_name='temperature',
            constraint=models.CheckConstraint(condition=models.Q(('value__lt', 100)), name='temperature_value_less_than_100'),
        ),
    ]
