"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

from django.core.management.utils import get_random_secret_key
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env file
load_dotenv()

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY", get_random_secret_key())

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DJANGO_DEBUG", default=0)

# should be a list of host/domain names that this Django site can serve.
ALLOWED_HOSTS = os.getenv("DJANGO_ALLOWED_HOSTS", default="localhost").split(",")

ROOT_URLCONF = "backend.urls"

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.gis",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "measurements",
    "measurement_collection",
    "measurement_analysis",
    "measurement_export.apps.MeasurementExportConfig",
    "campaigns",
    "api",
    "rest_framework",
    "rest_framework_gis",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

APPEND_SLASH = True

ROOT_URLCONF = "backend.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [Path(BASE_DIR) / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ]
        },
    }
]

WSGI_APPLICATION = "backend.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.contrib.gis.db.backends.postgis",
        "NAME": os.getenv("POSTGRES_DB", default="mydb"),
        "USER": os.getenv("POSTGRES_USER", default="myuser"),
        "PASSWORD": os.getenv("POSTGRES_PASSWORD", default="mypassword"),
        "HOST": os.getenv("POSTGRES_HOST", default="localhost"),
        "PORT": os.getenv("POSTGRES_PORT", default="5432"),
        "OPTIONS": {
            "pool": {
                "min_size": int(os.getenv("DJANGO_POOL_MIN_SIZE", "5")),
                "max_size": int(os.getenv("DJANGO_POOL_MAX_SIZE", "20")),
                "timeout": int(os.getenv("DJANGO_POOL_TIMEOUT", "60")),
            },
            "connect_timeout": int(os.getenv("DJANGO_CONNECT_TIMEOUT", "30")),
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = os.getenv("DJANGO_TIME_ZONE", default="UTC")

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "/api/static/"
STATIC_ROOT = Path(BASE_DIR) / "static"
MEDIA_URL = "/api/media/"
MEDIA_ROOT = Path(BASE_DIR) / "media"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# Setup Logger
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "[{name}] {levelname:8} {asctime} {module:10} {name}.{funcName}:{lineno}: {message}",
            "style": "{",
        },
        "default": {
            "format": "[{name}] {levelname:8} {asctime} {module}: {message}",
            "style": "{",
        },
        "simple": {
            "format": "[{name}] {levelname:8}: {message}",
            "style": "{",
        },
    },
    "handlers": {
        **(
            {
                "debug_file": {
                    "level": "DEBUG",
                    "class": "logging.FileHandler",
                    "filename": "logs/debug.log",
                    "formatter": "verbose",
                },
                "file": {
                    "level": "INFO",
                    "class": "logging.FileHandler",
                    "filename": "logs/info.log",
                    "formatter": "verbose",
                },
            }
            if os.getenv("DJANGO_LOG_TO_FILE", default="0") == "1"
            else {}
        ),
        "console": {
            "level": "DEBUG",
            "class": "logging.StreamHandler",
            "formatter": "default",
        },
    },
    "loggers": {
        "WATERWATCH": {
            "handlers": ["console", "debug_file"]
            if os.getenv("DJANGO_LOG_TO_FILE", default="0") == "1"
            else ["console"],
            "level": "DEBUG",
            "propagate": True,
        },
    },
}

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://redis:6379/1",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        },
    },
    "location_cache": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://redis:6379/2",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        },
    },
}
