# Generated by Django 5.2 on 2025-06-10 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['region'], name='campaigns_c_region_16212e_idx'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['start_time'], name='campaigns_c_start_t_e078f7_idx'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['end_time'], name='campaigns_c_end_tim_009a1a_idx'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['start_time', 'end_time'], name='campaigns_c_start_t_1f4e5a_idx'),
        ),
    ]
