# Generated by Django 5.2 on 2025-05-12 14:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("measurement_export", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="location",
            table="locations",
        ),
    ]
