# Generated by Django 5.2 on 2025-05-16 13:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("measurement_export", "0002_alter_location_table"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="location",
            options={
                "managed": False,
                "permissions": [("can_export", "can export measurements")],
            },
        ),
    ]
