# Generated by Django 5.2 on 2025-05-30 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement_export', '0004_preset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preset',
            name='filters',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
