# Generated by Django 5.2 on 2025-05-24 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_metric', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'measurements_testmetric',
                'managed': False,
            },
        ),
    ]
