# Generated by Django 5.2 on 2025-05-25 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measurement_collection', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestMetric',
        ),
    ]
