openapi: 3.0.0
servers:
  - description: SwaggerHub API Auto Mocking
    url: 'https://virtserver.swaggerhub.com/nicohammer-072/WATERWATCH_API/0.1.0'
  - url: 'https://api.waterwatch.tudelft.nl/api'
    description: Production server (public API for all users)
  - url: 'https://staging.waterwatch.tudelft.nl/api'
    description: Staging server (for testing new features)
  - url: 'http://localhost:8000/api'
    description: Local development
info:
  version: 1.0.0
  title: WATERWATCH API
  description: |-
    WATERWATCH is a citizen‑science platform for recording and analyzing drinking‑water temperature (and future sensor data like pH or turbidity).
    Public endpoints allow anyone to query measurements and campaigns.
    Protected operations (delete/update) require an API key or user credentials.
  contact:
    name: WATERWATCH
    email: waterwatch@tudelft.nl
    url: 'https://www.waterwatch.tudelft.nl'
  license:
    name: MIT
    url: 'https://opensource.org/licenses/MIT'
tags:
  - name: measurements
    description: 'Upload, query, and delete water‑temperature (and other sensor) data'
  - name: users
    description: 'User account operations (self‑registration, profile, delete own account)'
  - name: campaigns
    description: Manage and explore data‑collection campaigns
  - name: admins
    description: 'Admin‑only endpoints (full CRUD on users, measurements, and campaigns)'
paths:
  /measurements:
    get:
      tags: [measurements]
      summary: Retrieve all measurements.
      description: |
        Returns a list of all measurements. Supports optional filtering by date, location, campaign, etc.
      parameters: []
      responses:
        '200':
          description: A page of measurements.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Measurement'
        '400':
          description: Bad input parameter.
        '404':
          description: Not found.
  '/users/{userId}':
    parameters:
      - in: path
        name: userId
        required: true
        schema:
          type: string
          format: uuid
  '/campaigns/{campaignId}':
    parameters:
      - in: path
        name: campaignId
        required: true
        schema:
          type: string
          format: uuid

  /api/measurements/:
    get:
      tags: [measurements]
      summary: Retrieve all measurements
      responses:
        '200':
          description: A list of measurements
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Measurement'
    post:
      tags: [measurements]
      summary: Add a new measurement
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MeasurementPayload'
            example:
              timestamp: "2025-06-17T12:34:56.000Z"
              local_date: "2025-06-17"
              local_time: "14:34:56"
              location:
                type: "Point"
                coordinates: [4.895, 52.370]
              water_source: "well"
              temperature:
                sensor: "Analog Thermometer"
                value: 22.5
                time_waited: "00:05:00"
      responses:
        '201':
          description: Measurement created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Measurement'
        '400':
          $ref: '#/components/responses/BadRequest'

  /api/measurements/search/:
    post:
      tags: [measurements]
      summary: Search measurements
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MeasurementSearchRequest'
            example:
              start_date: "2025-01-01T00:00:00Z"
              end_date: "2025-06-17T23:59:59Z"
              metrics:
                - "temperature"
                - "humidity"
      responses:
        '200':
          description: Search results
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Measurement'
        '400':
          $ref: '#/components/responses/BadRequest'

  /api/measurements/temperatures/:
    post:
      tags: [measurements]
      summary: Retrieve temperature measurements
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TemperatureRequest'
            example:
              boundary_geometry:
                type: "Polygon"
                coordinates:
                  - [[4.88,52.36],[4.90,52.36],[4.90,52.38],[4.88,52.38],[4.88,52.36]]
              month: [0, 6]
      responses:
        '200':
          description: List of temperature values
          content:
            application/json:
              schema:
                type: array
                items:
                  type: number
        '400':
          $ref: '#/components/responses/BadRequest'
        '500':
          $ref: '#/components/responses/InternalError'

  /api/login/:
    post:
      tags: [users]
      summary: Authenticate and log in a user
      description: |
        Expects JSON with `username` and `password`.  
        Returns groups list on success.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
            example:
              username: "admin"
              password: "secret123"
      responses:
        '200':
          description: Successfully logged in
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginResponse'
        '400':
          $ref: '#/components/responses/BadCredentials'

  /api/logout/:
    post:
      tags: [users]
      summary: Log out the current user
      description: Invalid if not authenticated.
      responses:
        '200':
          description: Successfully logged out
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericDetail'
                example:
                  detail: "Successfully logged out."
        '400':
          description: User not logged in
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericDetail'
                example:
                  detail: "You're not logged in."

  /api/session/:
    get:
      tags: [users]
      summary: Check authentication status (sets CSRF cookie)
      responses:
        '200':
          description: Current auth state
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SessionResponse'

  /api/whoami/:
    get:
      tags: [users]
      summary: Get authenticated username
      responses:
        '200':
          description: Username or unauthenticated flag
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: '#/components/schemas/WhoAmIResponse'
                  - $ref: '#/components/schemas/SessionResponse'

  /api/user-permissions/:
    get:
      tags: [users]
      summary: List user's groups and permissions
      security:
        - cookieAuth: []
      responses:
        '200':
          description: User info
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserPermissionsResponse'
        '403':
          description: Forbidden (not authenticated)

  /api/health/:
    get:
      tags: [users]
      summary: Health check
      description: Returns status ok when server is up.
      responses:
        '200':
          description: Server healthy
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthResponse'

  /api/campaigns/active/:
    get:
      tags: [campaigns]
      summary: Retrieve active campaigns
      description: |
        Returns all campaigns active at the given datetime and within the specified location.
      parameters:
        - name: datetime
          in: query
          description: ISO‑8601 timestamp to filter campaigns by their start/end times
          required: true
          schema:
            type: string
            format: date-time
            example: "2025-06-17T12:00:00Z"
        - name: lat
          in: query
          description: Latitude to filter campaigns by region proximity
          required: true
          schema:
            type: number
            format: float
            example: 52.370
        - name: lng
          in: query
          description: Longitude to filter campaigns by region proximity
          required: true
          schema:
            type: number
            format: float
            example: 4.895
      responses:
        '200':
          description: A list of matching active campaigns
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ActiveCampaignsResponse'
              example:
                campaigns:
                  - id: 123
                    name: "Summer Promo"
                    description: "Discounts on all summer items"
                    start_time: "2025-06-01T00:00:00Z"
                    end_time: "2025-08-31T23:59:59Z"
                    region:
                      type: "Polygon"
                      coordinates:
                        - [[4.88,52.36],[4.90,52.36],[4.90,52.38],[4.88,52.38],[4.88,52.36]]
                  - id: 456
                    name: "Heat Wave Alert"
                    description: "Special campaigns during heat waves"
                    start_time: "2025-06-15T08:00:00Z"
                    end_time: "2025-06-20T20:00:00Z"
                    region: null
        '400':
          description: Invalid or missing datetime
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                error: "Invalid or missing datetime"

components:
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: sessionid

  responses:
    BadRequest:
      description: Invalid request parameters or payload
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
          example:
            error: "Invalid or missing parameter"
    InternalError:
      description: Internal server error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
          example:
            error: "Internal server error"
    BadCredentials:
      description: Missing or invalid username/password
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/GenericDetail'
          example:
            detail: "Invalid credentials."

  schemas:
    Measurement:
      type: object
      required:
        - id
        - timestamp
        - local_date
        - local_time
        - location
        - water_source
      properties:
        id:
          type: string
          format: uuid
        timestamp:
          type: string
          format: date-time
        local_date:
          type: string
          format: date
        local_time:
          type: string
          pattern: '^\\d{2}:\\d{2}:\\d{2}$'
        location:
          $ref: '#/components/schemas/GeoJSON'
        water_source:
          type: string
        temperature:
          nullable: true
          $ref: '#/components/schemas/TemperatureDetail'

    MeasurementPayload:
      type: object
      required:
        - timestamp
        - local_date
        - local_time
        - location
        - water_source
      properties:
        timestamp:
          type: string
          format: date-time
        local_date:
          type: string
          format: date
        local_time:
          type: string
          pattern: '^\\d{2}:\\d{2}:\\d{2}$'
        location:
          $ref: '#/components/schemas/GeoJSON'
        water_source:
          type: string
        temperature:
          nullable: true
          $ref: '#/components/schemas/TemperatureDetail'

    MeasurementSearchRequest:
      type: object
      properties:
        start_date:
          type: string
          format: date-time
        end_date:
          type: string
          format: date-time
        metrics:
          type: array
          items:
            type: string

    TemperatureRequest:
      type: object
      properties:
        boundary_geometry:
          $ref: '#/components/schemas/GeoJSON'
        month:
          oneOf:
            - type: integer
            - type: array
              items:
                type: integer

    TemperatureDetail:
      type: object
      required:
        - sensor
        - value
        - time_waited
      properties:
        sensor:
          type: string
        value:
          type: number
        time_waited:
          type: string
          pattern: '^\\d{2}:\\d{2}:\\d{2}$'

    GeoJSON:
      type: object
      required:
        - type
        - coordinates
      properties:
        type:
          type: string
        coordinates:
          type: array
          items: 
            type: number
    ErrorResponse:
      type: object
      properties:
        error:
          type: string

    LoginRequest:
      type: object
      required:
        - username
        - password
      properties:
        username:
          type: string
        password:
          type: string

    LoginResponse:
      type: object
      properties:
        detail:
          type: string
          example: "Successfully logged in."
        groups:
          type: array
          items:
            type: string

    GenericDetail:
      type: object
      properties:
        detail:
          type: string

    SessionResponse:
      type: object
      properties:
        isAuthenticated:
          type: boolean
          example: false

    WhoAmIResponse:
      type: object
      properties:
        username:
          type: string
          example: "admin"

    UserPermissionsResponse:
      type: object
      properties:
        username:
          type: string
          example: "alice"
        groups:
          type: array
          items:
            type: string
        permissions:
          type: array
          items:
            type: string
        is_superuser:
          type: boolean
          example: false

    HealthResponse:
      type: object
      properties:
        status:
          type: string
          enum: ["ok"]
          example: "ok"

    ActiveCampaignsResponse:
      type: object
      properties:
        campaigns:
          type: array
          items:
            $ref: '#/components/schemas/Campaign'

    Campaign:
      type: object
      required:
        - id
        - name
        - description
        - start_time
        - end_time
      properties:
        id:
          type: integer
        name:
          type: string
        description:
          type: string
        start_time:
          type: string
          format: date-time
        end_time:
          type: string
          format: date-time
        region:
          oneOf:
            - $ref: '#/components/schemas/GeoJSON'
            - type: 'object'
